name    'alkivi-ldap'
version '0.0.1'
source 'https://github.com/alkivi-sas/puppet-ldap'
author 'alkivi'
license 'LGPLv3'
summary 'Controls backupPC and clients'
description 'Setup backupPC and handle client configuration in puppet'
project_page 'https://github.com/alkivi-sas/puppet-ldap'
dependency 'puppetlabs/stdlib', '>3.x'
dependency 'puppetlabs/concat', '1.0.0'
dependency 'puppetlabs/apache', '>0.x'
dependency 'alkivi/alkivi_base', '>0.x'
